site_name: Esperanza STEM

nav:
  - Home: index.md
  - Python:
    - Why Python: python/whyPython.md
    - Introduction: python/introduction.md
    - Setting Up Trinket: python/trinket.md
    - The Turtle Library: python/turtle.md
    - Drawing a Square: python/simpleSquare.md
    - What Else Can a Turtle Do?: python/turtleTricks.md
    - Python Variables: python/variables.md
    - Using Variables: python/usingVariables.md
    - Drawing Four Squares: python/fourSquares.md
    - Exploring Loops: python/loops.md
    - Conditionals: python/conditionals.md
    - Lists: python/lists.md
    - Functions: python/functions.md
    - Variable Scope: python/scope.md
    - Exception Handling: python/tryExcept.md
    - Recursion: python/recursion.md
    - Towers of Hanoi: python/towers.md
    - Eight Queens: python/eight.md
  - MicroPython:
    - Raspberry Pi Pico: micropython/pico.md
    - Installing MicroPython: micropython/install.md
    - Thonny: micropython/thonny.md
    - Breadboard: micropython/breadboard.md
    - Blink Onboard LED: micropython/onboardBlink.md
    - Alternating LEDs: micropython/alternatingBlink.md
    - Button Press (Polling): micropython/buttonPressPoll.md
    - Button Press (Interrupt): micropython/buttonPressInterrupt.md
    - Pulse Width Modulation: micropython/pwm.md
    - Analog to Digital Converter: micropython/adc.md
    - Photo Resistor: micropython/photoResistor.md
    - Solutions:
      - Alternating LEDs: micropython/solutions/lab2.md
      - Button Press (Polling): micropython/solutions/lab3p.md
      - Button Press (Interrupt): micropython/solutions/lab3i.md
      - Pulse Width Modulation: micropython/solutions/lab4.md
      - Analog to Digital Converter: micropython/solutions/lab5.md
      - Photo Resistor: micropython/solutions/lab6.md
  - Robot Car: robotCar/makerPiRP2040Bot.md

theme:
  material

site_description: 'Resources for teaching Python to Esperanza Academy students.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Jim Tannenbaum'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/jetannenbaum/EsperanzaSTEM'

edit_uri: 'blob/master/docs'
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences

