site_name: Esperanza STEM

nav:
  - Home: index.md
  - Python:
    - Why Python: python/whyPython.md
    - Introduction: python/introduction.md
    - Setting Up Trinket: python/trinket.md
    - The Turtle Library: python/turtle.md
    - Drawing a Square: python/simpleSquare.md
    - What Else Can a Turtle Do?: python/turtleTricks.md
    - Python Variables: python/variables.md
    - Using Variables: python/usingVariables.md
    - Drawing Four Squares: python/fourSquares.md
    - Exploring Loops: python/loops.md
    - Conditionals: python/conditionals.md
    - Lists: python/lists.md
  - Robot Car: robotCar/makerPiRP2040Bot.md

theme:
  material

site_description: 'Resources for teaching Python to Esperanza Academy students.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Jim Tannenbaum'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/jetannenbaum/EsperanzaSTEM'

edit_uri: 'blob/master/docs'
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences

